language: python
python:
  - "2.7"
# command to install dependencies
install: pip install -r requirements.txt
addons:
  postgresql: 9.3
  apt:
    packages:
    - postgresql-9.3-postgis-2.3
# command to run tests
script: 
  - nosetests
